### ISSUE TITLE
I tried python 3.12 and the same error persists 

### ISSUE THREAD

**Issue by Kaira3535** [McDaived/AIMi#15]
I tried python 3.12 and the same error persists

**Comment by MrWaffleManTheGreat** [comment]
What fixed it for me was opening CMD and going to the directory that start.py is in, then typing " python start.py " (minus the quotations) and i had to run it a few times for it to install everything

**Comment by McDaived** [comment]
thxx alot for feedback ..

i promise i will fix this problem , but dont forget it varies according to the processors that can analyze the neural network .. but it still work fine .. and you have problem we didn't find it, and it will be fix soon.

can you try this plz 

3. **Optimazing For cs2** :


 Best Setting for CS2 and make sure use this crosshair or make your own dot crosshair, to make natural network more faster by give some space to analyse model.

1. import this crosshair is game setting ``CSGO-YE93T-V6tTU-Cxa9r-jCf7s-2XJaA ``

2. for best result use this setting

![image](https://github.com/McDaived/AIMi/assets/18085492/5fc8c79b-0dd5-4989-9223-9e93760f84a1)


**and please keep me informed about these matters so that i can improve it to make it good for use in all games.**
