### ISSUE TITLE
Crosshair bug

### ISSUE THREAD

**Issue by isvktt** [McDaived/AIMi#16]
When I'm in the game the crosshair just keeps locking, but when I minimize the game the crosshair keeps locking on the enemy outside the game, I disabled pointer precision, I couldn't deactivate rawinput, from what I know rawinput is automatically deactivated in cs2
my problem : https://www.youtube.com/watch?v=qjb0bsYVHV8

**Comment by McDaived** [comment]
it works as well for alot of people but it varies according to the processors that can analyze the neural network .. but it still work fine ..

**_can you try this and give me feedback .._**


1. remove python completely  and download latest version and install it by followin this steps : 

<details> 
        <summary>Fix Python</summary> 
    
***Download latest version of python then install it like this pictures..***

![](https://github.com/McDaived/AIMi/assets/18085492/d3217d15-7a18-4782-b8f3-d0cbe6acc41d)
![](https://github.com/McDaived/AIMi/assets/18085492/51b0660c-62f1-475b-8181-df1b9d7bbcdd)
![](https://github.com/McDaived/AIMi/assets/18085492/489a6c20-3729-4e9c-9ad2-e388e39c4284)

          
</details>

2. **Optimazing For cs2** :


 Best Setting for CS2 and make sure use this crosshair or make your own dot crosshair, to make natural network more faster by give some space to analyse model.

1. import this crosshair is game setting ``CSGO-YE93T-V6tTU-Cxa9r-jCf7s-2XJaA ``

2. for best result use this setting

![image](https://github.com/McDaived/AIMi/assets/18085492/5fc8c79b-0dd5-4989-9223-9e93760f84a1)


**and please keep me informed about these matters so that i can improve it to make it good for use in all games.**
