### ISSUE TITLE
CS2 NOT WORKING?!?!

### ISSUE THREAD

**Issue by MrWaffleManTheGreat** [McDaived/AIMi#17]
detection works fine, Im pretty sure its due to CS2 having raw input forced on at all times. I do not know if you can disable this in cs2

(side note to developer: have you thought of using RawAccel? to work around the raw input issue. i heard about it from one of the comments on this post on reddit: https://www.reddit.com/r/GlobalOffensive/comments/146lfxe/no_raw_input_option_in_cs2/ ) 

EDIT: raw accel did not seem to fix it.

**Comment by McDaived** [comment]
it works as well for alot of people but it varies according to the processors that can analyze the neural network .. but it still work fine ..




**_can you try this and give me feedback .._**

1. remove raw accel completely 
2. remove python completely  and download latest version and install it by followin this steps : 

<details> 
        <summary>Fix Python</summary> 
    
***Download latest version of python then install it like this pictures..***

![](https://github.com/McDaived/AIMi/assets/18085492/d3217d15-7a18-4782-b8f3-d0cbe6acc41d)
![](https://github.com/McDaived/AIMi/assets/18085492/51b0660c-62f1-475b-8181-df1b9d7bbcdd)
![](https://github.com/McDaived/AIMi/assets/18085492/489a6c20-3729-4e9c-9ad2-e388e39c4284)

          
</details>

3. **Optimazing For cs2** :


 Best Setting for CS2 and make sure use this crosshair or make your own dot crosshair, to make natural network more faster by give some space to analyse model.

1. import this crosshair is game setting ``CSGO-YE93T-V6tTU-Cxa9r-jCf7s-2XJaA ``

2. for best result use this setting

![image](https://github.com/McDaived/AIMi/assets/18085492/5fc8c79b-0dd5-4989-9223-9e93760f84a1)


**and please keep me informed about these matters so that i can improve it to make it good for use in all games.**
