### ISSUE TITLE
Safe or Bannable?

### ISSUE THREAD

**Issue by Synx400** [McDaived/AIMi#19]
Did anyone get vac ban on CS2 by using this AI Aimbot tool or (can I use this on Apex Legends and MW3 If this can be used then it is Safe or Not?)
Please let me know<3

**Comment by McDaived** [comment]
This isn't considered hacking in the games because it doesn't modify the game files
or interfere with the games, it only takes control on behalf of the user,
never access the memory of the games, so its practically invisible to "Anti-Cheat" sofware.

that is mean it safe 99% without ban, but avoid overwatch if it available in games. 

**_you will not get ban by anticheat .._**
