### ISSUE TITLE
AIMi How can I make it work like in the video?

### ISSUE THREAD

**Issue by Kaira3535** [McDaived/AIMi#2]
Yes, there's a slight vibration when I see the character, but I'm trying it in CS2, and it's not locking onto the character like in the video. I wonder why that could be? How can I make it work like in the video you shared?

**Comment by Kaira3535** [comment]
My CPU is an Intel i7 12650H and my GPU is an RTX3070 LAPTOP. I can't understand why it's not working properly as I'm certain I did everything correctly, especially since I've even disabled pointer precision in the mouse settings. No problem, I'll wait for you and hopefully, you'll release an update today :)

> It will be improved in the next releases, its a beta, as you know, it will be better more accurate in the next releases because it works very well for some people and it works well for me, **_it varies according to the processors that can analyze the neural network_** , thats okay, thank you for the clarification, i will work hard to solve this.

**Comment by McDaived** [comment]
Im checking it with the help of many people to fix these problems. 

if you get this messege [WARN:0@2.310], it's a warning issued by the opencv library because it's unable to recognize the CPU because it interferes with CUDA because GPU is disabled in this version, It's okay, it's just a warning, ignore this message because it doesnt stop the program from working, just a warning I will solve this bug in the next release.

this show to some people and may be one of the reasons for the inaccuracy, i will fix it thx for feedback

**Comment by McDaived** [comment]
It will work fine when I make the next version work on GPU by CUDA , because the GPU works more accurately than the CPU to analyzing the neural network.

**Comment by Kaira3535** [comment]
> Im checking it with the help of many people to fix these problems.
> 
> if you get this messege [WARN:0@2.310], it's a warning issued by the opencv library because it's unable to recognize the CPU because it interferes with CUDA because GPU is disabled in this version, It's okay, it's just a warning, ignore this message because it doesnt stop the program from working, just a warning I will solve this bug in the next release.
> 
> this show to some people and may be one of the reasons for the inaccuracy, i will fix it thx for feedback

ok good work :)
