### ISSUE TITLE
Raw Input and Pointer Precision is off but still aim to the ground...

### ISSUE THREAD

**Issue by Synx400** [McDaived/AIMi#20]
How to fix this bro on apex legends?
https://streamable.com/sry09s

**Comment by McDaived** [comment]
it will be better more accurate in the next releases because it's beta version and it works very well for some people and it works well for me,
it varies according to the processors that can analyze the neural network ,

**i will find how to fix that and please keep me informed about these matters so that i can improve it to make it good for use in all games.**

im doing everything to make it work to all users , i will fix everything soon as possible. thx for feedback .
