### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dev-masson** [McDaived/AIMi#5]
"It's not working for me, I have the cmd and the gui objects open on the second monitor, the targets are being detected but the aim doesn't move. Is there any configuration I can do?

I don't know if this influences, but this warning is appearing in my cmd:

[ WARN:0@5.911] global ocl4dnn_conv_spatial.cpp:1923 cv::dnn::ocl4dnn::OCL4DNNConvSpatial<float>::loadTunedConfig OpenCV(ocl4dnn): consider to specify kernel configuration cache directory through OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!"

**Comment by dev-masson** [comment]
obs: im trying on valorant

**Comment by memes231** [comment]
Same man i have this issue

**Comment by McDaived** [comment]
**PS: if you get this messege [WARN:0@x.xxx], it's a warning issued by the opencv library because it's unable to recognize the CPU because it interferes with CUDA because GPU is disabled in this version, It's okay, it's just a warning, ignore this message because it doesnt stop the program from working, just a warning I will solve this bug in the next release.**

it doesnt work now on Valorent at the present time, when it is improved, an improved version of it and the method of operation will be released to make it work on valo

**Comment by dev-masson** [comment]
Thank you for the response, I look forward to future updates, great work!
