### ISSUE TITLE
[Bug] When i enabled aimbot in Game screen, AI Detects but Not aim and slightly vibrate cursor in Counter Strike 2 and other games

### ISSUE THREAD

**Issue by memes231** [McDaived/AIMi#6]
Help me i want to fix this

**Comment by McDaived** [comment]
when use AIMi you will see slight vibration in aimbot because its a beta version, everything will be improved in the next releases, it will be better more accurate in the next releases because it works very well for some people and it works well for me, it varies according to the processors that can analyze the neural network , but still work fine .


i next release it will be better by using cuda gpu, with more improve and accurate 

thx for your feedback
