### ISSUE TITLE
Aim

### ISSUE THREAD

**Issue by leatll** [McDaived/AIMi#9]
Its detecting enemies. sometimes it will flick on them and not follow or flick to the sky or ground, is their a solution to this?

**Comment by leatll** [comment]
it works very well with google images but once im in a game it will detect any enemy and immediately flick to the sky or ground.

**Comment by McDaived** [comment]
it will be better more accurate in the next releases because it's beta version and it works very well for some people and it works well for me,
it varies according to the processors that can analyze the neural network ,

im doing everything to make it work to all users , i will fix everything soon as possible. thx for feedback .
